package com.zy.pms.mbg.mapper;

import com.zy.pms.model.PmsYl;
import com.zy.pms.model.PmsYlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmsYlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    int countByExample(PmsYlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    int deleteByExample(PmsYlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    int insert(PmsYl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    int insertSelective(PmsYl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    List<PmsYl> selectByExample(PmsYlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    PmsYl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    int updateByExampleSelective(@Param("record") PmsYl record, @Param("example") PmsYlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    int updateByExample(@Param("record") PmsYl record, @Param("example") PmsYlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    int updateByPrimaryKeySelective(PmsYl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    int updateByPrimaryKey(PmsYl record);
}