package com.zy.pms.mbg.mapper;

import com.zy.pms.model.PmsYldata;
import com.zy.pms.model.PmsYldataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmsYldataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    int countByExample(PmsYldataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    int deleteByExample(PmsYldataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    int insert(PmsYldata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    int insertSelective(PmsYldata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    List<PmsYldata> selectByExample(PmsYldataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    PmsYldata selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") PmsYldata record, @Param("example") PmsYldataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    int updateByExample(@Param("record") PmsYldata record, @Param("example") PmsYldataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    int updateByPrimaryKeySelective(PmsYldata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    int updateByPrimaryKey(PmsYldata record);
}