package com.zy.pms.model;

import java.io.Serializable;
import java.util.Date;

public class PmsYldata implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_yldata.id
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_yldata.yl_name
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    private String ylName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_yldata.yl_time
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    private Date ylTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_yldata.yl_simNo
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    private Integer ylSimno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_yldata.yl_temperature
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    private Integer ylTemperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_yldata.yl_currentData
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    private Float ylCurrentdata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_yldata.yl_dcdy
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    private Float ylDcdy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_yldata.yl_xl
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    private Float ylXl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_yldata.yl_xhqd
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    private Float ylXhqd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_yldata.yl_info
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    private String ylInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_yldata.id
     *
     * @return the value of pms_yldata.id
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_yldata.id
     *
     * @param id the value for pms_yldata.id
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_yldata.yl_name
     *
     * @return the value of pms_yldata.yl_name
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public String getYlName() {
        return ylName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_yldata.yl_name
     *
     * @param ylName the value for pms_yldata.yl_name
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public void setYlName(String ylName) {
        this.ylName = ylName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_yldata.yl_time
     *
     * @return the value of pms_yldata.yl_time
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public Date getYlTime() {
        return ylTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_yldata.yl_time
     *
     * @param ylTime the value for pms_yldata.yl_time
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public void setYlTime(Date ylTime) {
        this.ylTime = ylTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_yldata.yl_simNo
     *
     * @return the value of pms_yldata.yl_simNo
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public Integer getYlSimno() {
        return ylSimno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_yldata.yl_simNo
     *
     * @param ylSimno the value for pms_yldata.yl_simNo
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public void setYlSimno(Integer ylSimno) {
        this.ylSimno = ylSimno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_yldata.yl_temperature
     *
     * @return the value of pms_yldata.yl_temperature
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public Integer getYlTemperature() {
        return ylTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_yldata.yl_temperature
     *
     * @param ylTemperature the value for pms_yldata.yl_temperature
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public void setYlTemperature(Integer ylTemperature) {
        this.ylTemperature = ylTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_yldata.yl_currentData
     *
     * @return the value of pms_yldata.yl_currentData
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public Float getYlCurrentdata() {
        return ylCurrentdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_yldata.yl_currentData
     *
     * @param ylCurrentdata the value for pms_yldata.yl_currentData
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public void setYlCurrentdata(Float ylCurrentdata) {
        this.ylCurrentdata = ylCurrentdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_yldata.yl_dcdy
     *
     * @return the value of pms_yldata.yl_dcdy
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public Float getYlDcdy() {
        return ylDcdy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_yldata.yl_dcdy
     *
     * @param ylDcdy the value for pms_yldata.yl_dcdy
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public void setYlDcdy(Float ylDcdy) {
        this.ylDcdy = ylDcdy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_yldata.yl_xl
     *
     * @return the value of pms_yldata.yl_xl
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public Float getYlXl() {
        return ylXl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_yldata.yl_xl
     *
     * @param ylXl the value for pms_yldata.yl_xl
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public void setYlXl(Float ylXl) {
        this.ylXl = ylXl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_yldata.yl_xhqd
     *
     * @return the value of pms_yldata.yl_xhqd
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public Float getYlXhqd() {
        return ylXhqd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_yldata.yl_xhqd
     *
     * @param ylXhqd the value for pms_yldata.yl_xhqd
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public void setYlXhqd(Float ylXhqd) {
        this.ylXhqd = ylXhqd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_yldata.yl_info
     *
     * @return the value of pms_yldata.yl_info
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public String getYlInfo() {
        return ylInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_yldata.yl_info
     *
     * @param ylInfo the value for pms_yldata.yl_info
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public void setYlInfo(String ylInfo) {
        this.ylInfo = ylInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", ylName=").append(ylName);
        sb.append(", ylTime=").append(ylTime);
        sb.append(", ylSimno=").append(ylSimno);
        sb.append(", ylTemperature=").append(ylTemperature);
        sb.append(", ylCurrentdata=").append(ylCurrentdata);
        sb.append(", ylDcdy=").append(ylDcdy);
        sb.append(", ylXl=").append(ylXl);
        sb.append(", ylXhqd=").append(ylXhqd);
        sb.append(", ylInfo=").append(ylInfo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}