package com.zy.pms.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PmsYldataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public PmsYldataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andYlNameIsNull() {
            addCriterion("yl_name is null");
            return (Criteria) this;
        }

        public Criteria andYlNameIsNotNull() {
            addCriterion("yl_name is not null");
            return (Criteria) this;
        }

        public Criteria andYlNameEqualTo(String value) {
            addCriterion("yl_name =", value, "ylName");
            return (Criteria) this;
        }

        public Criteria andYlNameNotEqualTo(String value) {
            addCriterion("yl_name <>", value, "ylName");
            return (Criteria) this;
        }

        public Criteria andYlNameGreaterThan(String value) {
            addCriterion("yl_name >", value, "ylName");
            return (Criteria) this;
        }

        public Criteria andYlNameGreaterThanOrEqualTo(String value) {
            addCriterion("yl_name >=", value, "ylName");
            return (Criteria) this;
        }

        public Criteria andYlNameLessThan(String value) {
            addCriterion("yl_name <", value, "ylName");
            return (Criteria) this;
        }

        public Criteria andYlNameLessThanOrEqualTo(String value) {
            addCriterion("yl_name <=", value, "ylName");
            return (Criteria) this;
        }

        public Criteria andYlNameLike(String value) {
            addCriterion("yl_name like", value, "ylName");
            return (Criteria) this;
        }

        public Criteria andYlNameNotLike(String value) {
            addCriterion("yl_name not like", value, "ylName");
            return (Criteria) this;
        }

        public Criteria andYlNameIn(List<String> values) {
            addCriterion("yl_name in", values, "ylName");
            return (Criteria) this;
        }

        public Criteria andYlNameNotIn(List<String> values) {
            addCriterion("yl_name not in", values, "ylName");
            return (Criteria) this;
        }

        public Criteria andYlNameBetween(String value1, String value2) {
            addCriterion("yl_name between", value1, value2, "ylName");
            return (Criteria) this;
        }

        public Criteria andYlNameNotBetween(String value1, String value2) {
            addCriterion("yl_name not between", value1, value2, "ylName");
            return (Criteria) this;
        }

        public Criteria andYlTimeIsNull() {
            addCriterion("yl_time is null");
            return (Criteria) this;
        }

        public Criteria andYlTimeIsNotNull() {
            addCriterion("yl_time is not null");
            return (Criteria) this;
        }

        public Criteria andYlTimeEqualTo(Date value) {
            addCriterion("yl_time =", value, "ylTime");
            return (Criteria) this;
        }

        public Criteria andYlTimeNotEqualTo(Date value) {
            addCriterion("yl_time <>", value, "ylTime");
            return (Criteria) this;
        }

        public Criteria andYlTimeGreaterThan(Date value) {
            addCriterion("yl_time >", value, "ylTime");
            return (Criteria) this;
        }

        public Criteria andYlTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("yl_time >=", value, "ylTime");
            return (Criteria) this;
        }

        public Criteria andYlTimeLessThan(Date value) {
            addCriterion("yl_time <", value, "ylTime");
            return (Criteria) this;
        }

        public Criteria andYlTimeLessThanOrEqualTo(Date value) {
            addCriterion("yl_time <=", value, "ylTime");
            return (Criteria) this;
        }

        public Criteria andYlTimeIn(List<Date> values) {
            addCriterion("yl_time in", values, "ylTime");
            return (Criteria) this;
        }

        public Criteria andYlTimeNotIn(List<Date> values) {
            addCriterion("yl_time not in", values, "ylTime");
            return (Criteria) this;
        }

        public Criteria andYlTimeBetween(Date value1, Date value2) {
            addCriterion("yl_time between", value1, value2, "ylTime");
            return (Criteria) this;
        }

        public Criteria andYlTimeNotBetween(Date value1, Date value2) {
            addCriterion("yl_time not between", value1, value2, "ylTime");
            return (Criteria) this;
        }

        public Criteria andYlSimnoIsNull() {
            addCriterion("yl_simNo is null");
            return (Criteria) this;
        }

        public Criteria andYlSimnoIsNotNull() {
            addCriterion("yl_simNo is not null");
            return (Criteria) this;
        }

        public Criteria andYlSimnoEqualTo(Integer value) {
            addCriterion("yl_simNo =", value, "ylSimno");
            return (Criteria) this;
        }

        public Criteria andYlSimnoNotEqualTo(Integer value) {
            addCriterion("yl_simNo <>", value, "ylSimno");
            return (Criteria) this;
        }

        public Criteria andYlSimnoGreaterThan(Integer value) {
            addCriterion("yl_simNo >", value, "ylSimno");
            return (Criteria) this;
        }

        public Criteria andYlSimnoGreaterThanOrEqualTo(Integer value) {
            addCriterion("yl_simNo >=", value, "ylSimno");
            return (Criteria) this;
        }

        public Criteria andYlSimnoLessThan(Integer value) {
            addCriterion("yl_simNo <", value, "ylSimno");
            return (Criteria) this;
        }

        public Criteria andYlSimnoLessThanOrEqualTo(Integer value) {
            addCriterion("yl_simNo <=", value, "ylSimno");
            return (Criteria) this;
        }

        public Criteria andYlSimnoIn(List<Integer> values) {
            addCriterion("yl_simNo in", values, "ylSimno");
            return (Criteria) this;
        }

        public Criteria andYlSimnoNotIn(List<Integer> values) {
            addCriterion("yl_simNo not in", values, "ylSimno");
            return (Criteria) this;
        }

        public Criteria andYlSimnoBetween(Integer value1, Integer value2) {
            addCriterion("yl_simNo between", value1, value2, "ylSimno");
            return (Criteria) this;
        }

        public Criteria andYlSimnoNotBetween(Integer value1, Integer value2) {
            addCriterion("yl_simNo not between", value1, value2, "ylSimno");
            return (Criteria) this;
        }

        public Criteria andYlTemperatureIsNull() {
            addCriterion("yl_temperature is null");
            return (Criteria) this;
        }

        public Criteria andYlTemperatureIsNotNull() {
            addCriterion("yl_temperature is not null");
            return (Criteria) this;
        }

        public Criteria andYlTemperatureEqualTo(Integer value) {
            addCriterion("yl_temperature =", value, "ylTemperature");
            return (Criteria) this;
        }

        public Criteria andYlTemperatureNotEqualTo(Integer value) {
            addCriterion("yl_temperature <>", value, "ylTemperature");
            return (Criteria) this;
        }

        public Criteria andYlTemperatureGreaterThan(Integer value) {
            addCriterion("yl_temperature >", value, "ylTemperature");
            return (Criteria) this;
        }

        public Criteria andYlTemperatureGreaterThanOrEqualTo(Integer value) {
            addCriterion("yl_temperature >=", value, "ylTemperature");
            return (Criteria) this;
        }

        public Criteria andYlTemperatureLessThan(Integer value) {
            addCriterion("yl_temperature <", value, "ylTemperature");
            return (Criteria) this;
        }

        public Criteria andYlTemperatureLessThanOrEqualTo(Integer value) {
            addCriterion("yl_temperature <=", value, "ylTemperature");
            return (Criteria) this;
        }

        public Criteria andYlTemperatureIn(List<Integer> values) {
            addCriterion("yl_temperature in", values, "ylTemperature");
            return (Criteria) this;
        }

        public Criteria andYlTemperatureNotIn(List<Integer> values) {
            addCriterion("yl_temperature not in", values, "ylTemperature");
            return (Criteria) this;
        }

        public Criteria andYlTemperatureBetween(Integer value1, Integer value2) {
            addCriterion("yl_temperature between", value1, value2, "ylTemperature");
            return (Criteria) this;
        }

        public Criteria andYlTemperatureNotBetween(Integer value1, Integer value2) {
            addCriterion("yl_temperature not between", value1, value2, "ylTemperature");
            return (Criteria) this;
        }

        public Criteria andYlCurrentdataIsNull() {
            addCriterion("yl_currentData is null");
            return (Criteria) this;
        }

        public Criteria andYlCurrentdataIsNotNull() {
            addCriterion("yl_currentData is not null");
            return (Criteria) this;
        }

        public Criteria andYlCurrentdataEqualTo(Float value) {
            addCriterion("yl_currentData =", value, "ylCurrentdata");
            return (Criteria) this;
        }

        public Criteria andYlCurrentdataNotEqualTo(Float value) {
            addCriterion("yl_currentData <>", value, "ylCurrentdata");
            return (Criteria) this;
        }

        public Criteria andYlCurrentdataGreaterThan(Float value) {
            addCriterion("yl_currentData >", value, "ylCurrentdata");
            return (Criteria) this;
        }

        public Criteria andYlCurrentdataGreaterThanOrEqualTo(Float value) {
            addCriterion("yl_currentData >=", value, "ylCurrentdata");
            return (Criteria) this;
        }

        public Criteria andYlCurrentdataLessThan(Float value) {
            addCriterion("yl_currentData <", value, "ylCurrentdata");
            return (Criteria) this;
        }

        public Criteria andYlCurrentdataLessThanOrEqualTo(Float value) {
            addCriterion("yl_currentData <=", value, "ylCurrentdata");
            return (Criteria) this;
        }

        public Criteria andYlCurrentdataIn(List<Float> values) {
            addCriterion("yl_currentData in", values, "ylCurrentdata");
            return (Criteria) this;
        }

        public Criteria andYlCurrentdataNotIn(List<Float> values) {
            addCriterion("yl_currentData not in", values, "ylCurrentdata");
            return (Criteria) this;
        }

        public Criteria andYlCurrentdataBetween(Float value1, Float value2) {
            addCriterion("yl_currentData between", value1, value2, "ylCurrentdata");
            return (Criteria) this;
        }

        public Criteria andYlCurrentdataNotBetween(Float value1, Float value2) {
            addCriterion("yl_currentData not between", value1, value2, "ylCurrentdata");
            return (Criteria) this;
        }

        public Criteria andYlDcdyIsNull() {
            addCriterion("yl_dcdy is null");
            return (Criteria) this;
        }

        public Criteria andYlDcdyIsNotNull() {
            addCriterion("yl_dcdy is not null");
            return (Criteria) this;
        }

        public Criteria andYlDcdyEqualTo(Float value) {
            addCriterion("yl_dcdy =", value, "ylDcdy");
            return (Criteria) this;
        }

        public Criteria andYlDcdyNotEqualTo(Float value) {
            addCriterion("yl_dcdy <>", value, "ylDcdy");
            return (Criteria) this;
        }

        public Criteria andYlDcdyGreaterThan(Float value) {
            addCriterion("yl_dcdy >", value, "ylDcdy");
            return (Criteria) this;
        }

        public Criteria andYlDcdyGreaterThanOrEqualTo(Float value) {
            addCriterion("yl_dcdy >=", value, "ylDcdy");
            return (Criteria) this;
        }

        public Criteria andYlDcdyLessThan(Float value) {
            addCriterion("yl_dcdy <", value, "ylDcdy");
            return (Criteria) this;
        }

        public Criteria andYlDcdyLessThanOrEqualTo(Float value) {
            addCriterion("yl_dcdy <=", value, "ylDcdy");
            return (Criteria) this;
        }

        public Criteria andYlDcdyIn(List<Float> values) {
            addCriterion("yl_dcdy in", values, "ylDcdy");
            return (Criteria) this;
        }

        public Criteria andYlDcdyNotIn(List<Float> values) {
            addCriterion("yl_dcdy not in", values, "ylDcdy");
            return (Criteria) this;
        }

        public Criteria andYlDcdyBetween(Float value1, Float value2) {
            addCriterion("yl_dcdy between", value1, value2, "ylDcdy");
            return (Criteria) this;
        }

        public Criteria andYlDcdyNotBetween(Float value1, Float value2) {
            addCriterion("yl_dcdy not between", value1, value2, "ylDcdy");
            return (Criteria) this;
        }

        public Criteria andYlXlIsNull() {
            addCriterion("yl_xl is null");
            return (Criteria) this;
        }

        public Criteria andYlXlIsNotNull() {
            addCriterion("yl_xl is not null");
            return (Criteria) this;
        }

        public Criteria andYlXlEqualTo(Float value) {
            addCriterion("yl_xl =", value, "ylXl");
            return (Criteria) this;
        }

        public Criteria andYlXlNotEqualTo(Float value) {
            addCriterion("yl_xl <>", value, "ylXl");
            return (Criteria) this;
        }

        public Criteria andYlXlGreaterThan(Float value) {
            addCriterion("yl_xl >", value, "ylXl");
            return (Criteria) this;
        }

        public Criteria andYlXlGreaterThanOrEqualTo(Float value) {
            addCriterion("yl_xl >=", value, "ylXl");
            return (Criteria) this;
        }

        public Criteria andYlXlLessThan(Float value) {
            addCriterion("yl_xl <", value, "ylXl");
            return (Criteria) this;
        }

        public Criteria andYlXlLessThanOrEqualTo(Float value) {
            addCriterion("yl_xl <=", value, "ylXl");
            return (Criteria) this;
        }

        public Criteria andYlXlIn(List<Float> values) {
            addCriterion("yl_xl in", values, "ylXl");
            return (Criteria) this;
        }

        public Criteria andYlXlNotIn(List<Float> values) {
            addCriterion("yl_xl not in", values, "ylXl");
            return (Criteria) this;
        }

        public Criteria andYlXlBetween(Float value1, Float value2) {
            addCriterion("yl_xl between", value1, value2, "ylXl");
            return (Criteria) this;
        }

        public Criteria andYlXlNotBetween(Float value1, Float value2) {
            addCriterion("yl_xl not between", value1, value2, "ylXl");
            return (Criteria) this;
        }

        public Criteria andYlXhqdIsNull() {
            addCriterion("yl_xhqd is null");
            return (Criteria) this;
        }

        public Criteria andYlXhqdIsNotNull() {
            addCriterion("yl_xhqd is not null");
            return (Criteria) this;
        }

        public Criteria andYlXhqdEqualTo(Float value) {
            addCriterion("yl_xhqd =", value, "ylXhqd");
            return (Criteria) this;
        }

        public Criteria andYlXhqdNotEqualTo(Float value) {
            addCriterion("yl_xhqd <>", value, "ylXhqd");
            return (Criteria) this;
        }

        public Criteria andYlXhqdGreaterThan(Float value) {
            addCriterion("yl_xhqd >", value, "ylXhqd");
            return (Criteria) this;
        }

        public Criteria andYlXhqdGreaterThanOrEqualTo(Float value) {
            addCriterion("yl_xhqd >=", value, "ylXhqd");
            return (Criteria) this;
        }

        public Criteria andYlXhqdLessThan(Float value) {
            addCriterion("yl_xhqd <", value, "ylXhqd");
            return (Criteria) this;
        }

        public Criteria andYlXhqdLessThanOrEqualTo(Float value) {
            addCriterion("yl_xhqd <=", value, "ylXhqd");
            return (Criteria) this;
        }

        public Criteria andYlXhqdIn(List<Float> values) {
            addCriterion("yl_xhqd in", values, "ylXhqd");
            return (Criteria) this;
        }

        public Criteria andYlXhqdNotIn(List<Float> values) {
            addCriterion("yl_xhqd not in", values, "ylXhqd");
            return (Criteria) this;
        }

        public Criteria andYlXhqdBetween(Float value1, Float value2) {
            addCriterion("yl_xhqd between", value1, value2, "ylXhqd");
            return (Criteria) this;
        }

        public Criteria andYlXhqdNotBetween(Float value1, Float value2) {
            addCriterion("yl_xhqd not between", value1, value2, "ylXhqd");
            return (Criteria) this;
        }

        public Criteria andYlInfoIsNull() {
            addCriterion("yl_info is null");
            return (Criteria) this;
        }

        public Criteria andYlInfoIsNotNull() {
            addCriterion("yl_info is not null");
            return (Criteria) this;
        }

        public Criteria andYlInfoEqualTo(String value) {
            addCriterion("yl_info =", value, "ylInfo");
            return (Criteria) this;
        }

        public Criteria andYlInfoNotEqualTo(String value) {
            addCriterion("yl_info <>", value, "ylInfo");
            return (Criteria) this;
        }

        public Criteria andYlInfoGreaterThan(String value) {
            addCriterion("yl_info >", value, "ylInfo");
            return (Criteria) this;
        }

        public Criteria andYlInfoGreaterThanOrEqualTo(String value) {
            addCriterion("yl_info >=", value, "ylInfo");
            return (Criteria) this;
        }

        public Criteria andYlInfoLessThan(String value) {
            addCriterion("yl_info <", value, "ylInfo");
            return (Criteria) this;
        }

        public Criteria andYlInfoLessThanOrEqualTo(String value) {
            addCriterion("yl_info <=", value, "ylInfo");
            return (Criteria) this;
        }

        public Criteria andYlInfoLike(String value) {
            addCriterion("yl_info like", value, "ylInfo");
            return (Criteria) this;
        }

        public Criteria andYlInfoNotLike(String value) {
            addCriterion("yl_info not like", value, "ylInfo");
            return (Criteria) this;
        }

        public Criteria andYlInfoIn(List<String> values) {
            addCriterion("yl_info in", values, "ylInfo");
            return (Criteria) this;
        }

        public Criteria andYlInfoNotIn(List<String> values) {
            addCriterion("yl_info not in", values, "ylInfo");
            return (Criteria) this;
        }

        public Criteria andYlInfoBetween(String value1, String value2) {
            addCriterion("yl_info between", value1, value2, "ylInfo");
            return (Criteria) this;
        }

        public Criteria andYlInfoNotBetween(String value1, String value2) {
            addCriterion("yl_info not between", value1, value2, "ylInfo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pms_yldata
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 04 12:39:01 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pms_yldata
     *
     * @mbggenerated Tue Jun 04 12:39:01 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}