package com.zy.pms.model;

import java.io.Serializable;

public class PmsYl implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_yl.id
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_yl.yl_name
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    private String ylName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_yl.yl_sn
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    private Integer ylSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_yl.yl_sx
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    private Integer ylSx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_yl.yl_xx
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    private Integer ylXx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_yl.yl_waring_mode
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    private Integer ylWaringMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_yl.yl_sleeptime
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    private Integer ylSleeptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_yl.id
     *
     * @return the value of pms_yl.id
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_yl.id
     *
     * @param id the value for pms_yl.id
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_yl.yl_name
     *
     * @return the value of pms_yl.yl_name
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    public String getYlName() {
        return ylName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_yl.yl_name
     *
     * @param ylName the value for pms_yl.yl_name
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    public void setYlName(String ylName) {
        this.ylName = ylName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_yl.yl_sn
     *
     * @return the value of pms_yl.yl_sn
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    public Integer getYlSn() {
        return ylSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_yl.yl_sn
     *
     * @param ylSn the value for pms_yl.yl_sn
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    public void setYlSn(Integer ylSn) {
        this.ylSn = ylSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_yl.yl_sx
     *
     * @return the value of pms_yl.yl_sx
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    public Integer getYlSx() {
        return ylSx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_yl.yl_sx
     *
     * @param ylSx the value for pms_yl.yl_sx
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    public void setYlSx(Integer ylSx) {
        this.ylSx = ylSx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_yl.yl_xx
     *
     * @return the value of pms_yl.yl_xx
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    public Integer getYlXx() {
        return ylXx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_yl.yl_xx
     *
     * @param ylXx the value for pms_yl.yl_xx
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    public void setYlXx(Integer ylXx) {
        this.ylXx = ylXx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_yl.yl_waring_mode
     *
     * @return the value of pms_yl.yl_waring_mode
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    public Integer getYlWaringMode() {
        return ylWaringMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_yl.yl_waring_mode
     *
     * @param ylWaringMode the value for pms_yl.yl_waring_mode
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    public void setYlWaringMode(Integer ylWaringMode) {
        this.ylWaringMode = ylWaringMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_yl.yl_sleeptime
     *
     * @return the value of pms_yl.yl_sleeptime
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    public Integer getYlSleeptime() {
        return ylSleeptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_yl.yl_sleeptime
     *
     * @param ylSleeptime the value for pms_yl.yl_sleeptime
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    public void setYlSleeptime(Integer ylSleeptime) {
        this.ylSleeptime = ylSleeptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", ylName=").append(ylName);
        sb.append(", ylSn=").append(ylSn);
        sb.append(", ylSx=").append(ylSx);
        sb.append(", ylXx=").append(ylXx);
        sb.append(", ylWaringMode=").append(ylWaringMode);
        sb.append(", ylSleeptime=").append(ylSleeptime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}