package com.zy.pms.model;

import java.util.ArrayList;
import java.util.List;

public class PmsYlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    public PmsYlExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andYlNameIsNull() {
            addCriterion("yl_name is null");
            return (Criteria) this;
        }

        public Criteria andYlNameIsNotNull() {
            addCriterion("yl_name is not null");
            return (Criteria) this;
        }

        public Criteria andYlNameEqualTo(String value) {
            addCriterion("yl_name =", value, "ylName");
            return (Criteria) this;
        }

        public Criteria andYlNameNotEqualTo(String value) {
            addCriterion("yl_name <>", value, "ylName");
            return (Criteria) this;
        }

        public Criteria andYlNameGreaterThan(String value) {
            addCriterion("yl_name >", value, "ylName");
            return (Criteria) this;
        }

        public Criteria andYlNameGreaterThanOrEqualTo(String value) {
            addCriterion("yl_name >=", value, "ylName");
            return (Criteria) this;
        }

        public Criteria andYlNameLessThan(String value) {
            addCriterion("yl_name <", value, "ylName");
            return (Criteria) this;
        }

        public Criteria andYlNameLessThanOrEqualTo(String value) {
            addCriterion("yl_name <=", value, "ylName");
            return (Criteria) this;
        }

        public Criteria andYlNameLike(String value) {
            addCriterion("yl_name like", value, "ylName");
            return (Criteria) this;
        }

        public Criteria andYlNameNotLike(String value) {
            addCriterion("yl_name not like", value, "ylName");
            return (Criteria) this;
        }

        public Criteria andYlNameIn(List<String> values) {
            addCriterion("yl_name in", values, "ylName");
            return (Criteria) this;
        }

        public Criteria andYlNameNotIn(List<String> values) {
            addCriterion("yl_name not in", values, "ylName");
            return (Criteria) this;
        }

        public Criteria andYlNameBetween(String value1, String value2) {
            addCriterion("yl_name between", value1, value2, "ylName");
            return (Criteria) this;
        }

        public Criteria andYlNameNotBetween(String value1, String value2) {
            addCriterion("yl_name not between", value1, value2, "ylName");
            return (Criteria) this;
        }

        public Criteria andYlSnIsNull() {
            addCriterion("yl_sn is null");
            return (Criteria) this;
        }

        public Criteria andYlSnIsNotNull() {
            addCriterion("yl_sn is not null");
            return (Criteria) this;
        }

        public Criteria andYlSnEqualTo(Integer value) {
            addCriterion("yl_sn =", value, "ylSn");
            return (Criteria) this;
        }

        public Criteria andYlSnNotEqualTo(Integer value) {
            addCriterion("yl_sn <>", value, "ylSn");
            return (Criteria) this;
        }

        public Criteria andYlSnGreaterThan(Integer value) {
            addCriterion("yl_sn >", value, "ylSn");
            return (Criteria) this;
        }

        public Criteria andYlSnGreaterThanOrEqualTo(Integer value) {
            addCriterion("yl_sn >=", value, "ylSn");
            return (Criteria) this;
        }

        public Criteria andYlSnLessThan(Integer value) {
            addCriterion("yl_sn <", value, "ylSn");
            return (Criteria) this;
        }

        public Criteria andYlSnLessThanOrEqualTo(Integer value) {
            addCriterion("yl_sn <=", value, "ylSn");
            return (Criteria) this;
        }

        public Criteria andYlSnIn(List<Integer> values) {
            addCriterion("yl_sn in", values, "ylSn");
            return (Criteria) this;
        }

        public Criteria andYlSnNotIn(List<Integer> values) {
            addCriterion("yl_sn not in", values, "ylSn");
            return (Criteria) this;
        }

        public Criteria andYlSnBetween(Integer value1, Integer value2) {
            addCriterion("yl_sn between", value1, value2, "ylSn");
            return (Criteria) this;
        }

        public Criteria andYlSnNotBetween(Integer value1, Integer value2) {
            addCriterion("yl_sn not between", value1, value2, "ylSn");
            return (Criteria) this;
        }

        public Criteria andYlSxIsNull() {
            addCriterion("yl_sx is null");
            return (Criteria) this;
        }

        public Criteria andYlSxIsNotNull() {
            addCriterion("yl_sx is not null");
            return (Criteria) this;
        }

        public Criteria andYlSxEqualTo(Integer value) {
            addCriterion("yl_sx =", value, "ylSx");
            return (Criteria) this;
        }

        public Criteria andYlSxNotEqualTo(Integer value) {
            addCriterion("yl_sx <>", value, "ylSx");
            return (Criteria) this;
        }

        public Criteria andYlSxGreaterThan(Integer value) {
            addCriterion("yl_sx >", value, "ylSx");
            return (Criteria) this;
        }

        public Criteria andYlSxGreaterThanOrEqualTo(Integer value) {
            addCriterion("yl_sx >=", value, "ylSx");
            return (Criteria) this;
        }

        public Criteria andYlSxLessThan(Integer value) {
            addCriterion("yl_sx <", value, "ylSx");
            return (Criteria) this;
        }

        public Criteria andYlSxLessThanOrEqualTo(Integer value) {
            addCriterion("yl_sx <=", value, "ylSx");
            return (Criteria) this;
        }

        public Criteria andYlSxIn(List<Integer> values) {
            addCriterion("yl_sx in", values, "ylSx");
            return (Criteria) this;
        }

        public Criteria andYlSxNotIn(List<Integer> values) {
            addCriterion("yl_sx not in", values, "ylSx");
            return (Criteria) this;
        }

        public Criteria andYlSxBetween(Integer value1, Integer value2) {
            addCriterion("yl_sx between", value1, value2, "ylSx");
            return (Criteria) this;
        }

        public Criteria andYlSxNotBetween(Integer value1, Integer value2) {
            addCriterion("yl_sx not between", value1, value2, "ylSx");
            return (Criteria) this;
        }

        public Criteria andYlXxIsNull() {
            addCriterion("yl_xx is null");
            return (Criteria) this;
        }

        public Criteria andYlXxIsNotNull() {
            addCriterion("yl_xx is not null");
            return (Criteria) this;
        }

        public Criteria andYlXxEqualTo(Integer value) {
            addCriterion("yl_xx =", value, "ylXx");
            return (Criteria) this;
        }

        public Criteria andYlXxNotEqualTo(Integer value) {
            addCriterion("yl_xx <>", value, "ylXx");
            return (Criteria) this;
        }

        public Criteria andYlXxGreaterThan(Integer value) {
            addCriterion("yl_xx >", value, "ylXx");
            return (Criteria) this;
        }

        public Criteria andYlXxGreaterThanOrEqualTo(Integer value) {
            addCriterion("yl_xx >=", value, "ylXx");
            return (Criteria) this;
        }

        public Criteria andYlXxLessThan(Integer value) {
            addCriterion("yl_xx <", value, "ylXx");
            return (Criteria) this;
        }

        public Criteria andYlXxLessThanOrEqualTo(Integer value) {
            addCriterion("yl_xx <=", value, "ylXx");
            return (Criteria) this;
        }

        public Criteria andYlXxIn(List<Integer> values) {
            addCriterion("yl_xx in", values, "ylXx");
            return (Criteria) this;
        }

        public Criteria andYlXxNotIn(List<Integer> values) {
            addCriterion("yl_xx not in", values, "ylXx");
            return (Criteria) this;
        }

        public Criteria andYlXxBetween(Integer value1, Integer value2) {
            addCriterion("yl_xx between", value1, value2, "ylXx");
            return (Criteria) this;
        }

        public Criteria andYlXxNotBetween(Integer value1, Integer value2) {
            addCriterion("yl_xx not between", value1, value2, "ylXx");
            return (Criteria) this;
        }

        public Criteria andYlWaringModeIsNull() {
            addCriterion("yl_waring_mode is null");
            return (Criteria) this;
        }

        public Criteria andYlWaringModeIsNotNull() {
            addCriterion("yl_waring_mode is not null");
            return (Criteria) this;
        }

        public Criteria andYlWaringModeEqualTo(Integer value) {
            addCriterion("yl_waring_mode =", value, "ylWaringMode");
            return (Criteria) this;
        }

        public Criteria andYlWaringModeNotEqualTo(Integer value) {
            addCriterion("yl_waring_mode <>", value, "ylWaringMode");
            return (Criteria) this;
        }

        public Criteria andYlWaringModeGreaterThan(Integer value) {
            addCriterion("yl_waring_mode >", value, "ylWaringMode");
            return (Criteria) this;
        }

        public Criteria andYlWaringModeGreaterThanOrEqualTo(Integer value) {
            addCriterion("yl_waring_mode >=", value, "ylWaringMode");
            return (Criteria) this;
        }

        public Criteria andYlWaringModeLessThan(Integer value) {
            addCriterion("yl_waring_mode <", value, "ylWaringMode");
            return (Criteria) this;
        }

        public Criteria andYlWaringModeLessThanOrEqualTo(Integer value) {
            addCriterion("yl_waring_mode <=", value, "ylWaringMode");
            return (Criteria) this;
        }

        public Criteria andYlWaringModeIn(List<Integer> values) {
            addCriterion("yl_waring_mode in", values, "ylWaringMode");
            return (Criteria) this;
        }

        public Criteria andYlWaringModeNotIn(List<Integer> values) {
            addCriterion("yl_waring_mode not in", values, "ylWaringMode");
            return (Criteria) this;
        }

        public Criteria andYlWaringModeBetween(Integer value1, Integer value2) {
            addCriterion("yl_waring_mode between", value1, value2, "ylWaringMode");
            return (Criteria) this;
        }

        public Criteria andYlWaringModeNotBetween(Integer value1, Integer value2) {
            addCriterion("yl_waring_mode not between", value1, value2, "ylWaringMode");
            return (Criteria) this;
        }

        public Criteria andYlSleeptimeIsNull() {
            addCriterion("yl_sleeptime is null");
            return (Criteria) this;
        }

        public Criteria andYlSleeptimeIsNotNull() {
            addCriterion("yl_sleeptime is not null");
            return (Criteria) this;
        }

        public Criteria andYlSleeptimeEqualTo(Integer value) {
            addCriterion("yl_sleeptime =", value, "ylSleeptime");
            return (Criteria) this;
        }

        public Criteria andYlSleeptimeNotEqualTo(Integer value) {
            addCriterion("yl_sleeptime <>", value, "ylSleeptime");
            return (Criteria) this;
        }

        public Criteria andYlSleeptimeGreaterThan(Integer value) {
            addCriterion("yl_sleeptime >", value, "ylSleeptime");
            return (Criteria) this;
        }

        public Criteria andYlSleeptimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("yl_sleeptime >=", value, "ylSleeptime");
            return (Criteria) this;
        }

        public Criteria andYlSleeptimeLessThan(Integer value) {
            addCriterion("yl_sleeptime <", value, "ylSleeptime");
            return (Criteria) this;
        }

        public Criteria andYlSleeptimeLessThanOrEqualTo(Integer value) {
            addCriterion("yl_sleeptime <=", value, "ylSleeptime");
            return (Criteria) this;
        }

        public Criteria andYlSleeptimeIn(List<Integer> values) {
            addCriterion("yl_sleeptime in", values, "ylSleeptime");
            return (Criteria) this;
        }

        public Criteria andYlSleeptimeNotIn(List<Integer> values) {
            addCriterion("yl_sleeptime not in", values, "ylSleeptime");
            return (Criteria) this;
        }

        public Criteria andYlSleeptimeBetween(Integer value1, Integer value2) {
            addCriterion("yl_sleeptime between", value1, value2, "ylSleeptime");
            return (Criteria) this;
        }

        public Criteria andYlSleeptimeNotBetween(Integer value1, Integer value2) {
            addCriterion("yl_sleeptime not between", value1, value2, "ylSleeptime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pms_yl
     *
     * @mbggenerated do_not_delete_during_merge Fri May 17 14:33:26 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pms_yl
     *
     * @mbggenerated Fri May 17 14:33:26 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}